version: "3"
services:
  r_project:
    build: .
    volumes:
      - ./data:/usr/src/app/data
      - ./images:/usr/src/app/images
      - ./main.R:/usr/src/app/main.R
      - ./output:/usr/src/app/output
    env_file: .env
    command: Rscript main.R
